package com.endrawan.cageprotector

object Config {
    val SYSTEM_STATUS_STANDBY = 0
    val SYSTEM_STATUS_WARNING = 1
    val SYSTEM_STATUS_DANGER = 2
    val SYSTEM_STATUS_DOOR_OPENED = 3
    val SYSTEM_STATUS_30_MIN_SAFE = 4
    val SYSTEM_STATUS_FINGERPRINT_ENROLL = 5
    val SYSTEM_STATUS_CALIBRATE_MPU6050 = 6

    val FINGERPRINT_ENROLL_STATUS_WAITING = 0 // Ready to enroll
    val FINGERPRINT_ENROLL_STATUS_ENROLLING = 1 // Start enrolling
    val FINGERPRINT_ENROLL_STATUS_SUCCESS = 2 // Enroll success
    val FINGERPRINT_ENROLL_STATUS_FAILED = 3 // Enroll failed try again

    val FINGERPRINT_ENROLL_STEPS_PUT_FINGER = 1
    val FINGERPRINT_ENROLL_STEPS_REMOVE_FINGER = 2
    val FINGERPRINT_ENROLL_STEPS_PUT_FINGER_AGAIN = 3
    val FINGERPRINT_ENROLL_STEPS_DONE = 4

    val DB_ENDPOINT_SYSTEM_STATUS = "system_status"
    val DB_ENDPOINT_ALERT_STATUS = "alert_status"
//    val DB_ENDPOINT_FINGERPRINT = "fingerprint"
    val DB_ENPOINT_FINGERPRINT_ENROLLMENT_STATUS = "fingerprint/enroll_status"
    val DB_ENDPOINT_LAST_UPDATED_ANDROID = "last_updated_android"
}